function ProyectoController ($scope) {
    $scope.proyectos = [
         {id: "alyosha", titulo : "Alyosha!",
        descripcion : "La estudiante de intercambio Alyosha Stalina ha estado asistiendo a una escuela japonesa secundaria durante tres meses. Ella viene de la nación de Solessia, pero todavía no logra encajar con los otros estudiantes debido a su actitud hostil y fría. No se podía esperar más, ya que Alyosha realmente es una asesina entrenada que ha ido asesinando gente desde que tenía cinco años de edad. Su última y más reciente misión es asesinar al presidente de Solessia que asistirá a la escuela secundaria donde se ha infiltrado durante tres meses. Sin embargo, la misión es cancelada y se le ordenó permanecer como una estudiante normal. Lo único que Alyosha saber hacer es asesinar, y nunca ha aprendido a ser una adolescente normal. ¿Será Alyosha capaz de completar la misión más difícil que le han dado?",
        img : "Img/Proyectos/Otras/alyosha.jpg"},
        {id: "BaitoSakiWa", titulo : "Arihisa Aokura",
        descripcion : "Arihisa Aokura necesita dinero. Necesita ese dinero para poder ayudar a su familia huérfana y ganarse la vida al mismo tiempo. Buscando en internet por un buen trabajo, encuentra un anuncio para un trabajo de medio tiempo en una malvada organización. Al ver que la paga era muy buena y que tenía bastantes beneficios, decide arriesgarse y presentarse a la entrevista. De alguna manera termina siendo contratado y ahora tiene que trabajar como un secuaz dentro de la malvada organización Antares. ¿Será capaz de sobrevivir a los ataques violentos en las misiones en contra de los héroes mientras trata de mantener a sus hermanos y hermanas huérfanos?", 
         img : "Img/Proyectos/Otras/baito%20saki.jpg"},
        {id: "BokuToRune", titulo : "Boku To Rune To Aoarachi",
        descripcion : "Souichi es un estudiante de arte, un día vio una pintura increíble en su universidad que lo hizo desear estudiar como aprendiz de aquel artista. Sin embargo, cuando fue a buscar que le enseñara, el hombre no lo aceptó. Poco tiempo después se encontró con la nieta de aquel artista, una niña rubia y de ojos azules llamada Rune. Era una pequeña muy energética, que lo llevó a jugar con ella en los alrededores con ella. Pronto, Souichi se enteró de la verdad... La pintura que lo había impresionado tanto no había sido obra del artista sino de Rune. Ella es la artista de quien él quiere aprender.", 
         img : "Img/Proyectos/Otras/boku%20to%20rune.png"},
        {id: "Carcaptor", titulo : "Carcaptor Sakura - Clear Card Arc",
        descripcion : "Luego de que Sakura Kinomoto recolectara cada carta y las convirtiese en sus amigas y aliadas usando el poder de su estrella todo volvió a la normalidad. Sin embargo eso solo fue el inicio del fin. Ahora, iniciando la secundaria y reencontrándose con su persona más importante, Sakura se enfrenta a un nuevo sueño premonitorio y a un nuevo misterio: Las cartas que tanto luchó por recolectar están, vacías.", 
         img : "Img/Proyectos/Otras/sakura%20card%20captor.jpg"},
        {id: "Chousuinou", titulo : "Chousuinou Key",
        descripcion : "", 
         img : "Img/Proyectos/Otras/chousuinou%20kei.jpg"},
        {id: "Dainana", titulo : "Dainana Joshikai Houkou",
        descripcion : "Takagi y Kanemura son dos estudiantes normales en un Japón de un futuro cercano, en el cual muchas cosas que ahora nos parecerían totalmente increíbles e inusuales, ellas se las toman con la mayor calma del mundo.", 
         img : "Img/Proyectos/Otras/dainana%20joshikai.jpg"},
        {id: "Diamon", titulo : "Diamon No Ace",
        descripcion : "Eijun Sawamura es un pitcher que entra en un prestigioso instituto, donde conoce a Kazuya Miyuki, un catcher brillante. Junto con el resto del equipo de béisbol del centro tratarán de ganar los campeonatos nacionales mediante su gran esfuerzo y dedicación.", 
         img : "Img/Proyectos/Otras/Diamond%20no%20Ace.jpg"},
        {id: "Domestic", titulo : "Domestic Na Kanojo",
        descripcion : "Esta noche, Natsuo perdio su virginidad. ?Su pareja? Su nombre es Rui y el apenas la conocio hoy despues de la escuela. Ella es quien trajo toda esta situacion, afirmando que simplemente queria ganar conocimiento sobre el sexo. Ella no quiere empezar una relacion, ni le importa Natsuo. Despues, Natsuo se siente culpable por perder su virginidad con una chica que particularmente no le gusta. Sobre todo, le hace sentir que traiciono a su enamorada, su maestra de secundaria, Hina. !Una historia de un peculiar triangulo amoroso se desarrolla con Natsuo, Rui y Hina, terminando siendo parte de la misma familia!", 
         img : "Img/Proyectos/Otras/domestic%20na%20kanojo.jpg"},
        {id: "Doubutsu", titulo : "Doubutsu No Kuni",
        descripcion : "Bienvenido al mundo de los animales . En este mundo , existe miles de animales a excepción de un hombre . Es decir, hasta que un extraño bebé fue encontrado por el joven mapache Monoko . Ahora, es el deber de ella ser la madre del niño en este mundo donde el fuerte come y el débil se come. ", 
         img : "Img/Proyectos/Otras/doubutsu%20no%20kuni.png"},
        {id: "Duel!", titulo : "Duel!",
        descripcion : "El lema de vida de Minori fue siempre sonreir sin importar las dificultades. Como sea, su personalidad dulce en su intento de hacer amigos ha logrado que abusen constantemente y poniéndola al límite de la ruptura, Midori comienza a ceder por la presión hasta que es salvada por una hermosa chica llamada Alice La aventura de Minori para convertirse en una mujer con fuerte voluntad comienza ahora", 
         img : "Img/Proyectos/Otras/duel!.jpg"},
        {id: "FairyTail", titulo : "Fairy Tail",
        descripcion : "Un día, Lucy Heartfilia, una joven maga de 17 años de edad especializada en la magia de espíritus estelares, huye de su hogar y viaja al reino de Fiore para cumplir su sueño de unirse al gremio de magos Fairy Tail. En el camino conoce a Natsu Dragneel, un joven que busca a Igneel , y que viaja acompañado de su mejor amigo, un gato parlante llamado Happy.", 
         img : "Img/Proyectos/Otras/fairy%20tail.jpg"},
        {id: "FTZero", titulo : "Fairy Tail Zero",
        descripcion : "Historia Extra de Hiro Mashima, donde se cuenta el nacimiento de Fairy Tail como gremio, además de los acontecimientos que dieron origen al mismo.", 
         img : "Img/Proyectos/Otras/fairy%20tail%20zero.jpg"},
        {id: "FireBrigade", titulo : "Fire Brigade Of Flames",
        descripcion : "Un inexplicable fenómeno de gente que de forma misteriosa estalla en llamas asalta a la humanidad, Shinra Kusakabe, un chico que desea convertirse en héroe se une al escuadrón especial de bomberos con el fin salvar a la humanidad y de descubrir el misterio detrás de su pasado.", 
         img : "Img/Proyectos/Otras/fire%20brigade%20of%20flames.jpg"},
        {id: "GaitouAlice", titulo : "Gaitou Alice",
        descripcion : "Tras el primer año de secundaria como del estudiante, Arisugawa Hikaru, se convierte en un cuento de Gaitou: Un ladrón quien sólo se aparece en lo sueño y se roba la oscuridad de los corazones de las personas. Hikaru, uno de los Gaitou, persigue a Gai conejos, un demonio de clase baja que busca la oscuridad en los humanos. Con la ayuda de su compañero, Ban, Hikaru protege a la gente de caer en la desesperación, sin embargo, el juego apenas comienza.", 
         img : "Img/Proyectos/Otras/gaitou%20alice.jpg"},
        {id: "GohanShiyo", titulo : "Gohan Shiyo!",
        descripcion : "Desde que sus padres se van a divorciar , Natsumi tuvo que salir de su casa y fue transferido a una escuela primaria de abordar , alojarse en un dormitorio. Todos sus compañeros de clase en la residencia de estudiantes parecen estar en todo tipo de situaciones . El dormitorio es famoso por su deliciosa comida . El que dirige el dormitorio es el tío de Natsumi , Takuro . Aunque son los niños , porque son niños, muchos continúa. Pero ya que son los niños , todo lo que necesitan es un poco de comida para comer! Pero aún así, la convivencia es difícil ...", 
         img : "Img/Proyectos/Otras/gohan%20shiyo.jpg"},
        {id: "Hoshino", titulo : "Hoshino, Me O Tsubutte",
        descripcion : "Desde que sus padres se van a divorciar , Natsumi tuvo que salir de su casa y fue transferido a una escuela primaria de abordar , alojarse en un dormitorio. Todos sus compañeros de clase en la residencia de estudiantes parecen estar en todo tipo de situaciones . El dormitorio es famoso por su deliciosa comida . El que dirige el dormitorio es el tío de Natsumi , Takuro . Aunque son los niños , porque son niños, muchos continúa. Pero ya que son los niños , todo lo que necesitan es un poco de comida para comer! Pero aún así, la convivencia es difícil ...", 
         img : "Img/Proyectos/Otras/hoshino.jpg"},
        {id: "KillerMaid", titulo : "I Am A Killer Maid",
        descripcion : "Hao Ping Qiong es un mangaka poco conocido que trabaja con entregas semanales. Un dia, un amigo lo sorprende diciendo que ha contrarado a un ama de casa para que limpie su apartamento. Xiao Bai Cai, una chica muy dulce y agradable, se pone a trabajar inmediatamente, limpiando todo y preparando una comida para Hao Ping. Pero cuando se despiertan al día siguiente, ¡se da cuenta de que ha cambiado de cuerpo con ella! Y que, encima de todo, ¡la dulce Xiao Bai Cai resulta ser una de las mejores asesinas del mundo! ¡Así es como comienzan sus aventuras y la diversión!", 
         img : "Img/Proyectos/Otras/i%20am%20a%20killer%20maid.jpg"},
        {id: "Kakushigoto", titulo : "Kakushigoto",
        descripcion : "Hao Ping Qiong es un mangaka poco conocido que trabaja con entregas semanales. Un dia, un amigo lo sorprende diciendo que ha contrarado a un ama de casa para que limpie su apartamento. Xiao Bai Cai, una chica muy dulce y agradable, se pone a trabajar inmediatamente, limpiando todo y preparando una comida para Hao Ping. Pero cuando se despiertan al día siguiente, ¡se da cuenta de que ha cambiado de cuerpo con ella! Y que, encima de todo, ¡la dulce Xiao Bai Cai resulta ser una de las mejores asesinas del mundo! ¡Así es como comienzan sus aventuras y la diversión!", 
         img : "Img/Proyectos/Otras/kakushigoto.jpg"},
        {id: "Nanohana", titulo : "Nanohana No Kare",
        descripcion : "Cuando Nanoka estaba en la secundaria, consiguió su primera confesión. Sintiendo que ese era el chico gustaba de verdad, empezó a salir con él. Sólo para descubrir más tarde que él sólo la utilizó para lucirse frente a sus amigos. Traicionada, Nanoka está ahora en el liceo y evita tener otra relación. Aunque un encuentro con desconocido en un restaurante de comida rápida pronto la haría cambiar de opinión. Tanto ella como el desconocido fueron traicionados en sus primeras relaciones... y esto trae una sensación diferente en su corazón. Después de ver al extraño otra vez en las calles, hace su primera confesión con él. Sólo para descubrir que son de dos mundos diferentes.", 
         img : "Img/Proyectos/Otras/nanohana.png"},
        {id: "OnePiece", titulo : "One Piece",
        descripcion : "La historia  trata sobre Monkey D. Luffy, un pirata el cual ha comido la Gomu Gomu No Mi, Fruta del Diablo la cual lo vuelve un hombre de goma. Junto a su tripulación deciden adentrarse en las aventuras que le deparan el océano, mientras hacen la búsqueda del mayor tesoro dejado por el Rey de los Piratas Gol D. Roger: el One Piece.", 
         img : "Img/Proyectos/Otras/one%20piece.jpg"},
        {id: "RozenMaiden", titulo : "Rozen Maiden",
        descripcion : "La historia comienza con Jun, un chico que vive aislado en su habitación y acostumbra a adquirir juguetes supuestamente malditos por Internet. Un día recibe una misteriosa carta que dice: ¿Le darás cuerda? ¿No le darás cuerda?, y distraídamente elige la primera opción. Así es como obtiene a Shinku, una hermosa y refinada muñeca que, luego de darle cuerda, cobra vida y dice ser la quinta Rozen Maiden.", 
         img : "Img/Proyectos/Otras/one%20piece.jpg"},
        {id: "SamonKun", titulo : "Samon-Kun Wa Summoner",
        descripcion : "", 
         img : "Img/Proyectos/Otras/samon%20kun.png"},
        {id: "Shinmai", titulo : "Shinmai Fukei Kiruku-Sa",
        descripcion : "Conozcan a la pequeña Estación de Policía de rechazados, que consiste en Kanjuuro el Jefe sarcástico, Haruki-senpai el típico oficial pervertido que no falta en este mundo, y Kiruko-san, la oficial nueva.... Quien casualmente resulto ser una Ex-Mercenaria mal de la cabeza. Con todo esto, nuestros héroes tienen que combatir contra la inseguridad de las calles y los malhechores que acechan la ciudad Nagashima para apoderarse de esta misma. ¿Qué le deparará el futuro a nuestra querida e inocente Kiruko-san?", 
         img : "Img/Proyectos/Otras/kiruko%20san.png"},
        {id: "ShounenShoujo", titulo : "Shounen Shoujo",
        descripcion : "Un chico de primaria esta aburrido de la monotoneidad de la vida y de la sociedad, en donde nadie tiene individualdiad y continuamente estamos forzados a parecernos entre nosotros. Pero su momento de ser especial, distinto del resto, llega cuando le diagnostican una rara y nueva enfermedad. No hay ninguna cura existente aun y los casos son muy escasos, ya que todos los niños que la padecen mueren a los 12 años. Pensando que es el nuevo protagonista de su historia, que va a destacar entre la marea de gente pide a los medicos que la enfermedad se nombre por él.", 
         img : "Img/Proyectos/Otras/shounen%20shoujo.jpg"},
        {id: "SonoToki", titulo : "Sono Toki",
        descripcion : "", 
         img : "Img/Proyectos/Otras/sono%20toki.jpg"},
        {id: "Takkoku", titulo : "Takkoku!!!",
        descripcion : "", 
         img : "Img/Proyectos/Otras/takkoku.jpg"},
        {id: "Tohai", titulo : "Tohai",
        descripcion : "No todas las personas saben que uno de los jugadores de Mahjong mas talentosos y despiadados en la ciudad es un joven chico que va a la preparatoria. Kei es un adolescente de pocas palabras, pero sus habilidades de observación, increíble poder de voluntad y experiencia en el juego le permiten sobrevivir en un mundo de poderosos, ricos y peligrosos personajes. Actualmente Kei esta escondiendo una chica llamada Amina, que ha entrado en el país ilegalmente, y protegiéndola de ser deportada. Pasa sus días durmiendo en clase y sus noches jugando en partidas de apuestas altas de Mahjong, esperando a que un oponente digno llegue.", 
         img : "Img/Proyectos/Otras/tohai.png"},
        {id: "Tsugumomo", titulo : "Tsugumomo",
        descripcion : "", 
         img : "Img/Proyectos/Otras/tsugumomo.jpg"},
        {id: "WhiteAlbum", titulo : "White Album",
        descripcion : "La historia gira entorno a Touya, quien tiene una nueva novia -Yuki Morikawa-, pero antes de entrar a la Universidad ella hace su debut como una idol. ¿Qué pasará en su relación con este nuevo desarrollo de acontecimientos? ¿Y qué pasará con la idol actual, Rina Ogata, quien ha puesto sus ojos en Touya? *Huele a School Days*", 
         img : "Img/Proyectos/Otras/white%20album.png"},
        {id: "WhyAre", titulo : "Why Are You Here Sensei!?",
        descripcion : "Secuela del One Shot <Golden Times>, donde vemos las aventuras amorosas y prohibidas de un estudiante con su sensei, la cual resulta ser su madre.", 
         img : "Img/Proyectos/Otras/sensei.jpg"},
        {id: "YuY", titulo : "Yu Yu Hakusho",
        descripcion : "Yusuke Urameshi, un chico de catorce años un poco gamberro es atropellado por un coche cuando intentaba salvar la vida de un niño pequeño. Al ser atropellado, no sobrevive y muere. Entonces es cuando Botan le dice que su muerte no estaba prevista asi que no va ni al cielo ni al infierno, por lo cual se queda en la tierra como fantasma. Botan le dice de hacer una prueba para volver a la vida, la consigue superar y entonces es cuando le encomiendan la tarea de ser detective espiritual, con lo cual tendrá que resolver varios casos utilizando poderes espirituales que le dan.", 
         img : "Img/Proyectos/Otras/yu%20yu%20hakusho.jpg"}
    ];
    $scope.listaactivos = [
         {id: "#alyosha",titulo : "Alyosha!",img : "Img/Proyectos/Alyosha.png"},
         {id: "#BaitoSakiWa",titulo : "Baito Saki Wa Aku No Sochiki",img : "Img/Proyectos/BaitoSakiWa.png"},
         {id: "#BokuToRune",titulo : "Boku To Rune To Aoarachi",img : "Img/Proyectos/BokuToRune.png"},
         {id: "#Carcaptor",titulo : "Carcaptor Sakura - Clear Card Arc",img : "Img/Proyectos/Carcaptor.png"},
         {id: "#Chousuinou",titulo : "Chousuinou Key",img : "Img/Proyectos/Chousuinou.png"},
         {id: "#Dainana",titulo : "Dainana Joshikai Houkou",img : "Img/Proyectos/Dainana.png"},
         {id: "#Diamon",titulo : "Diamon No Ace",img : "Img/Proyectos/Diamon.png"},
         {id: "#Domestic",titulo : "Domestic Na Kanojo",img : "Img/Proyectos/Domestic.png"},
         {id: "#Doubutsu",titulo : "Doubutsu No Kuni",img : "Img/Proyectos/Doubutsu.png"},
         {id: "#Duel!",titulo : "Duel!",img : "Img/Proyectos/Duel!.png"},
         {id: "#FairyTail",titulo : "Fairy Tail",img : "Img/Proyectos/FairyTail.png"},
         {id: "#FTZero",titulo : "Fairy Tail Zero",img : "Img/Proyectos/FTZero.png"},
         {id: "#FireBrigade",titulo : "Fire Brigade Of Flames",img : "Img/Proyectos/FireBrigade.png"},
         {id: "#GaitouAlice",titulo : "Gaitou Alice",img : "Img/Proyectos/GaitouAlice.png"},
         {id: "#GohanShiyo",titulo : "Gohan Shiyo!",img : "Img/Proyectos/GohanShiyo.png"},
         {id: "#Hoshino",titulo : "Hoshino, Me O Tsubutte",img : "Img/Proyectos/Hoshino.png"},
         {id: "#KillerMaid",titulo : "I Am A Killer Maid",img : "Img/Proyectos/KillerMaid.png"},
         {id: "#Kakushigoto",titulo : "Kakushigoto",img : "Img/Proyectos/Kakushigoto.png"},
         {id: "#Nanohana",titulo : "Nanohana No Kare",img : "Img/Proyectos/Nanohana.png"},
         {id: "#OnePiece",titulo : "One Piece",img : "Img/Proyectos/OnePiece.png"},
         {id: "21",titulo : "Uroka Na Tenshi Wa Akuma To Odoru",img : "Img/Proyectos/Odoru.png"},
         {id: "#RozenMaiden",titulo : "Rozen Maiden",img : "Img/Proyectos/RozenMaiden.png"},
         {id: "#SamonKun",titulo : "Samon-Kun Wa Summoner",img : "Img/Proyectos/SamonKun.png"},
         {id: "#Shinmai",titulo : "Shinmai Fukei Kiruku-San",img : "Img/Proyectos/Shinmai.png"},
         {id: "#ShounenShoujo",titulo : "Shounen Shoujo",img : "Img/Proyectos/ShounenShoujo.png"},
         {id: "#SonoToki",titulo : "Sono Toki, Kimi Ga Naita",img : "Img/Proyectos/SonoToki.png"},
         {id: "#Takkoku",titulo : "Takkoku!!!",img : "Img/Proyectos/Takkoku.png"},
         {id: "#Tohai",titulo : "Tohai",img : "Img/Proyectos/Tohai.png"},
         {id: "#Tsugumomo",titulo : "Tsugumomo",img : "Img/Proyectos/Tsugumomo.png"},
         {id: "#WhiteAlbum",titulo : "White Album",img : "Img/Proyectos/WhiteAlbum.png"},
         {id: "#WhyAre",titulo : "Why Are You Here Sensei!?",img : "Img/Proyectos/WhyAre.png"},
         {id: "#YuY",titulo : "Yu Yu Hakusho",img : "Img/Proyectos/YuY.png"}
     ];

     $scope.listafinalizados = [
         {id: "F1",titulo : "Assassination Classroom!",img : "Img/Proyectos/Classroom.png"},
         {id: "F2",titulo : "Naruto Gaiden",img : "Img/Proyectos/NarutoGaiden.png"},
         {id: "F3",titulo : "Toumei Ningene No Tsukurikata",img : "Img/Proyectos/ToumeiNingen.png"}
     ];
}

// function ListadoController ($scope) {

// }
